"""Niagara Renderer Actions action definitions."""

from __future__ import annotations

from .. import ActionDef


_NIAGARA_RENDERER_ACTIONS = [
    ActionDef(id="niagara.get_renderer_summary", command="niagara_get_renderer_summary", tags=("niagara", "renderer", "summary", "mesh", "material", "binding", "read", "introspect"), description="Read Niagara renderer classes, mesh slots, material overrides, enabled state, and core attribute bindings.", input_schema={"type":"object","properties":{"system_path":{"type":"string"},"emitter_name":{"type":"string"},"renderer_index":{"type":"integer"},"renderer_type":{"type":"string","enum":["sprite","mesh","ribbon","light"]}},"required":["system_path"]}, examples=({"system_path":"/Game/FX/NS_Papers","renderer_type":"mesh"},), capabilities=("read",)),
    ActionDef(id="niagara.remove_renderer", command="niagara_remove_renderer", tags=("niagara", "renderer", "remove", "write"), description="Remove a Niagara renderer by index or unique type.", input_schema={"type":"object","properties":{"system_path":{"type":"string"},"emitter_name":{"type":"string"},"renderer_index":{"type":"integer"},"renderer_type":{"type":"string","enum":["sprite","mesh","ribbon","light"]}},"required":["system_path"]}, examples=({"system_path":"/Game/FX/NS_Papers","renderer_type":"sprite"},), risk="moderate"),
    ActionDef(id="niagara.set_renderer_mesh", command="niagara_set_renderer_mesh", tags=("niagara", "renderer", "mesh", "set", "write"), description="Set mesh renderer static mesh and optional scale/rotation/pivot.", input_schema={"type":"object","properties":{"system_path":{"type":"string"},"emitter_name":{"type":"string"},"renderer_index":{"type":"integer"},"renderer_type":{"type":"string","enum":["mesh"]},"mesh_path":{"type":"string"},"mesh_slot":{"type":"integer"},"scale":{"type":"array","items":{"type":"number"}},"rotation":{"type":"array","items":{"type":"number"}},"pivot_offset":{"type":"array","items":{"type":"number"}}},"required":["system_path","mesh_path"]}, examples=({"system_path":"/Game/FX/NS_Papers","renderer_type":"mesh","mesh_path":"/Engine/BasicShapes/Plane.Plane","scale":[0.08,0.11,0.02]},), risk="moderate"),
    ActionDef(id="niagara.set_renderer_material", command="niagara_set_renderer_material", tags=("niagara", "renderer", "material", "set", "write"), description="Set sprite/ribbon material or mesh override material.", input_schema={"type":"object","properties":{"system_path":{"type":"string"},"emitter_name":{"type":"string"},"renderer_index":{"type":"integer"},"renderer_type":{"type":"string","enum":["sprite","mesh","ribbon"]},"material_path":{"type":"string"},"material_slot":{"type":"integer"},"enable_override":{"type":"boolean"}},"required":["system_path","material_path"]}, examples=({"system_path":"/Game/FX/NS_Papers","renderer_type":"mesh","material_path":"/Game/tmp/M_OfficePaper_White.M_OfficePaper_White"},), risk="moderate"),
    ActionDef(id="niagara.set_renderer_binding", command="niagara_set_renderer_binding", tags=("niagara", "renderer", "binding", "attribute", "set", "write"), description="Set an FNiagaraVariableAttributeBinding renderer property; aliases include position/color/velocity/scale/mesh_orientation/renderer_enabled/renderer_visibility_tag/mesh_index.", input_schema={"type":"object","properties":{"system_path":{"type":"string"},"emitter_name":{"type":"string"},"renderer_index":{"type":"integer"},"renderer_type":{"type":"string","enum":["sprite","mesh","ribbon","light"]},"binding_name":{"type":"string"},"variable_name":{"type":"string"}},"required":["system_path","binding_name","variable_name"]}, examples=({"system_path":"/Game/FX/NS_Papers","renderer_type":"mesh","binding_name":"scale","variable_name":"Particles.Scale"},), risk="moderate"),
]
